
stdout.txt: banned.zsh
stdout.txt: indentation.py
stdout.txt: Makefile
stdout.txt: runner.zsh
stdout.txt: shebang.py
stdout.txt: style.zsh
stdout.txt: test.py
	TASK=test.py zsh runner.zsh > stdout.txt
